---
title: "Prepare like table 5: sex and gendered indices association with WHIIRS"
output: 
  html_document:
    toc: true
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages}
library(tidyverse)
library(survey)
library(plyr)
library(dplyr)
library(factoextra)
library(labelled)
library(memisc)
library(sjlabelled)
library(boot)
library(glmnet)
library(UpSetR)
library(naniar)
library(RColorBrewer)
library(jtools)
library(reshape2)
# source p-value formatting function
source("format_pvalue.R")
```

# Load and prepare the dataset

```{r}
folder_path <- "/Users/tamarsofer/Library/CloudStorage/OneDrive-BethIsraelLaheyHealth/Ongoing_papers/2022_gendered_indices"
dat_no_indices <- readRDS(file.path(folder_path, "Data/Data_with_miss.Rds"))

# the data with missing values:
# load the prepared dataset with indices
dat_miss <- readRDS(file.path(folder_path, "Data/Data_complete_case_with_indices.Rds"))


# load the imputed dataset with indices
dat_imp <- readRDS(file.path(folder_path, "Data/Data_imputed_with_indices.Rds"))

print(paste("The complete case dataset has", nrow(dat_miss), "individuals"))
print(paste("The imputed dataset has", nrow(dat_imp), "individuals"))

# because of the survey sampling design, we need to "merge" 
# the complete case dataset with design variables of the complete dataset
dat <- merge(dat_miss, 
             dat_no_indices[,c("ID", "STRAT" ,"PSU_ID", "WEIGHT_FINAL_NORM_OVERALL")], 
             by = c("ID", "STRAT" ,"PSU_ID", "WEIGHT_FINAL_NORM_OVERALL"), all = TRUE)

dat_imp <- merge(dat_imp, 
                 dat_no_indices[,c("ID", "WEIGHT_FINAL_NORM_OVERALL", "PSU_ID")], 
                 by = c("ID"))

nrow(dat) == nrow(dat_imp)
```
# add scaled indices to describe effect per 1 SD increase

```{r}
survey_cc <- svydesign(id = ~PSU_ID,
                          strata = ~STRAT,
                          weights = ~WEIGHT_FINAL_NORM_OVERALL,
                          nest = TRUE,
                          data = dat)
survey_cc <- subset(survey_cc, complete.cases(dat))

survey_imp <- svydesign(id = ~PSU_ID,
                          strata = ~STRAT,
                          weights = ~WEIGHT_FINAL_NORM_OVERALL,
                          nest = TRUE,
                          data = dat_imp)

cur_mean <- svymean(~GISE, survey_cc)[1]
cur_sd <- sqrt(svyvar(~GISE, survey_cc)[1])
dat_miss$GISE_scaled <- (dat_miss$GISE - cur_mean)/cur_sd

cur_mean <- svymean(~GIPSE, survey_cc)[1]
cur_sd <- sqrt(svyvar(~GIPSE, survey_cc)[1])
dat_miss$GIPSE_scaled <- (dat_miss$GIPSE - cur_mean)/cur_sd

for (suffix in c("", ".1", ".2", ".3", ".4")){
  cur_mean <- svymean(as.formula(paste0("~GISE", suffix)), survey_imp)[1]
  cur_sd <- sqrt(svyvar(as.formula(paste0("~GISE", suffix)), survey_imp)[1])
  dat_imp[[paste0("GISE_scaled", suffix)]] <- (dat_imp[[paste0("GISE", suffix)]] - cur_mean)/cur_sd

  cur_mean <- svymean(as.formula(paste0("~GIPSE", suffix)), survey_imp)[1]
  cur_sd <- sqrt(svyvar(as.formula(paste0("~GIPSE", suffix)), survey_imp)[1])
  dat_imp[[paste0("GIPSE_scaled", suffix)]] <- (dat_imp[[paste0("GIPSE", suffix)]] - cur_mean)/cur_sd
}


# recompute the survey objects:
dat <- merge(dat_miss, 
             dat_no_indices[,c("ID", "STRAT" ,"PSU_ID", "WEIGHT_FINAL_NORM_OVERALL")], 
             by = c("ID", "STRAT" ,"PSU_ID", "WEIGHT_FINAL_NORM_OVERALL"), all = TRUE)

survey_cc <- svydesign(id = ~PSU_ID,
                          strata = ~STRAT,
                          weights = ~WEIGHT_FINAL_NORM_OVERALL,
                          nest = TRUE,
                          data = dat)
survey_cc <- subset(survey_cc, complete.cases(dat))

survey_imp <- svydesign(id = ~PSU_ID,
                          strata = ~STRAT,
                          weights = ~WEIGHT_FINAL_NORM_OVERALL,
                          nest = TRUE,
                          data = dat_imp)


```
# Prepare model variables

```{r}
model1 <- c("Age", "Center", "Background", "Sex")
model2 <- c("Age", "Center", "Background", "Sex", "GISE_scaled")
model3 <- c("Age", "Center", "Background", "Sex", "GIPSE_scaled")

# models 4 and 5 include components of the primary and secondary indices:
model4 <- c(model1, "Marital_status",
                    "Income_level", 
                    "Employment_status", 
                    "Occupation", 
                    "Education",
                    "Current_Health_insurance", 
                    "Language_pref", 
                    "Language_acculturation", 
                    "Social_acculturation", 
                    "Ethnic_identity_score", 
                    "Years_in_US")
model5 <- c(model4, c("CESD9", "STAI10"))

# for stratified model
model2_sex_strat <- setdiff(model2,  "Sex")
model3_sex_strat <-  setdiff(model3,  "Sex")


```

# prepare "like" table 5: evaluate models
```{r}

# function to extract the estimated effect of an exposure on a binary outcome
extract_one_exp <- function(mod, exposure, round_digit = 2){
   est <- summary(mod)$coef
   confint <- confint(mod)
  
  ind <- grep(exposure, rownames(est))
  
  df_out <- data.frame(exposure = exposure, 
                       est = round(est[ind, "Estimate"],round_digit), 
                       CI = paste0("(", round(confint[ind, 1], round_digit),
                                   ",",round(confint[ind, 2], round_digit) , ")"),
                       pval = formatC(est[ind, "Pr(>|t|)"], digits = round_digit, format = "E"), 
                       paper_pval= format_pvalue(est[ind, "Pr(>|t|)"]))
 

  return(df_out)
}



table5 <- data.frame(row.names = c(paste0("all_model_",1:5 ),
                                   paste0("male_model_", 2:3),
                                   paste0("female_model_", 2:3)),
                     male_eff = rep(NA, 9),
                     male_CI = NA,
                     male_pval = NA,
                     index_eff = NA,
                     index_CI = NA,
                     index_pval = NA, 
                     index_paper_pval = NA)

# fit models (sex combined)
model1_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model1, collapse = "+"))), design = survey_cc, family = gaussian())

model2_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model2, collapse = "+"))), design = survey_cc, family = gaussian())

model3_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model3, collapse = "+"))), design = survey_cc, family = gaussian())

model4_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model4, collapse = "+"))), design = survey_cc, family = gaussian())

model5_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model5, collapse = "+"))), design = survey_cc, family = gaussian())

for (i in 1:5){
  table5[paste0("all_model_", i), 
         c("male_eff", "male_CI", "male_pval", "male_paper_pval")] <- 
             extract_one_exp(get(paste0("model", i, "_fit")) , 
                                 exposure = "Sex")[c("est", "CI", "pval", "paper_pval")]
}

table5["all_model_2",
       c("index_eff", "index_CI",  "index_pval", "index_paper_pval")]  <- 
          extract_one_exp(get(paste0("model2_fit")) , 
                                 exposure = "GISE_scaled")[c("est", "CI", "pval", "paper_pval")]

table5["all_model_3",
       c("index_eff", "index_CI", "index_pval", "index_paper_pval")]  <- 
          extract_one_exp(get(paste0("model3_fit")) , 
                                 exposure = "GIPSE_scaled")[c("est", "CI", "pval", "paper_pval")]


survey_cc_male <- subset(survey_cc, Sex == "Male")
survey_cc_female <- subset(survey_cc, Sex == "Female")

model2_male_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model2_sex_strat, collapse = "+"))), design = survey_cc_male, family = gaussian())

model3_male_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model3_sex_strat, collapse = "+"))), design = survey_cc_male, family = gaussian())

model2_female_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model2_sex_strat, collapse = "+"))), design = survey_cc_female, family = gaussian())

model3_female_fit <- svyglm(formula = as.formula(paste0("WHIIRS~", paste(model3_sex_strat, collapse = "+"))), design = survey_cc_female, family = gaussian())

for (i in 2:3){
  for (sex in c("male", "female")){
    type <- ifelse(i == 2, "GISE", "GIPSE")
      table5[paste0(sex, "_model_", i), 
         c("index_eff", "index_CI", "index_pval", "index_paper_pval")]  <- 
          extract_one_exp(get(paste0("model", i, "_", sex, "_fit")) , 
                                 exposure = paste0(type, "_scaled"))[c("est", "CI", "pval", "paper_pval")]
    
  }

}

table5

write.csv(table5, file = file.path(folder_path, "Results/like_table5_whiirs.csv"))

```


# Table 4 using imputed dataset (Supplementary Table 1)

Functions that will help us
```{r}
# can't use the pool function from the MI package
# instead write a function that fit a model on the 5 datasets, and applies Rubin's rule.
# for simplicity, assume WHIIRS is outcome, assume 5 imputations

rubins_rule <- function(ests, ses, round_digit = 2){
  vars <- ses^2
  m <- length(ses)
  
  pooled_est <- mean(ests)
  within_imp_var <- mean(vars)
  between_imp_var <- sum((vars - within_imp_var)^2)/(m -1)
  
  pooled_var <- within_imp_var + (1+1/m)*between_imp_var
  pooled_se <- sqrt(pooled_var)
  
  F_test_stat <- pooled_est^2/pooled_var
  F_df1 <- 1
  r <- (1 + 1/m)*between_imp_var/pooled_est
  F_df2 <- (m - 1)*(1 + 1/r)^2
  
  F_pval <- pf(F_test_stat, F_df1, F_df2, lower.tail = FALSE)
  
  CI <- paste0("(", round(pooled_est - 1.96*pooled_se, round_digit), ",", 
               round(pooled_est + 1.96*pooled_se, round_digit), ")")
  
  return(data.frame(est = round(pooled_est, round_digit), CI = CI, pval = F_pval))
  
}


extract_one_exp_mi <- function(survey_imp,  model_vars, exposure, 
                               round_digit = 2){
  
  imp_suffix <-  c("", ".1", ".2", ".3", ".4")
  est <- se <- rep(NA, 5)
  names(est) <- names(se) <-  imp_suffix
  for (i in 1:length(imp_suffix)){
    suffix <- imp_suffix[i]
    cur_fit <- svyglm(formula = as.formula(paste0("WHIIRS", suffix, "~", paste(paste0(model_vars, suffix), collapse = "+"))), design = survey_imp, family = gaussian())
    
    fit_est <- summary(cur_fit)$coef
    ind_exp <- grep(exposure, rownames(fit_est))
    est[i] <- fit_est[ind_exp, "Estimate"]
    se[i] <- fit_est[ind_exp, "Std. Error"]
    
  }
  
  # now apply Rubin's rule
  
  res <- rubins_rule(est, se, round_digit = round_digit)

  
  df_out <- data.frame(exposure = exposure, 
                       est = res[["est"]], 
                       CI = res[["CI"]], 
                       pval = formatC(res[["pval"]], digits = round_digit, format = "E"), 
                       paper_pval = format_pvalue(res[["pval"]]))
 

  return(df_out)
}



```




And prepare the table using imputed data:
```{r}



table5_imp <- data.frame(row.names = c(paste0("all_model_",1:5 ),
                                   paste0("male_model_", 2:3),
                                   paste0("female_model_", 2:3)),
                     male_eff = rep(NA, 9),
                     male_95_CI = NA,
                     male_pval = NA,
                     index_eff = NA,
                     index_95_CI = NA,
                     index_pval = NA, 
                     index_paper_pval = NA)


table5_imp["all_model_1", c("male_eff", "male_95_CI", "male_pval", "male_paper_pval")] <- extract_one_exp_mi(survey_imp, model1, "Sex")[, c("est", "CI", "pval", "paper_pval")]

table5_imp["all_model_2", c("male_eff", "male_95_CI", "male_pval", "male_paper_pval")] <- extract_one_exp_mi(survey_imp, model2, "Sex")[, c("est", "CI", "pval", "paper_pval")]

table5_imp["all_model_2", c("index_eff", "index_95_CI", "index_pval", "index_paper_pval")] <- extract_one_exp_mi(survey_imp, model2, "GISE_scaled")[, c("est", "CI", "pval", "paper_pval")]

table5_imp["all_model_3", c("male_eff", "male_95_CI", "male_pval", "male_paper_pval")] <- extract_one_exp_mi(survey_imp, model3, "Sex")[, c("est", "CI", "pval", "paper_pval")]

table5_imp["all_model_3", c("index_eff", "index_95_CI", "index_pval", "index_paper_pval")] <- extract_one_exp_mi(survey_imp, model3, "GIPSE_scaled")[, c("est", "CI", "pval", "paper_pval")]


table5_imp["all_model_4", c("male_eff", "male_95_CI", "male_pval", "male_paper_pval")] <- extract_one_exp_mi(survey_imp, model4, "Sex")[, c("est", "CI", "pval", "paper_pval")]

table5_imp["all_model_5", c("male_eff", "male_95_CI", "male_pval", "male_paper_pval")] <- extract_one_exp_mi(survey_imp, model5, "Sex")[, c("est", "CI", "pval", "paper_pval")]



survey_imp_male <- subset(survey_imp, Sex == "Male")
survey_imp_female <- subset(survey_imp, Sex == "Female")



table5_imp["male_model_2", c("index_eff", "index_95_CI", "index_pval", "index_paper_pval")] <- extract_one_exp_mi(survey_imp_male, setdiff(model2, "Sex"), "GISE_scaled")[, c("est", "CI", "pval", "paper_pval")]


table5_imp["male_model_3", c("index_eff", "index_95_CI", "index_pval", "index_paper_pval")] <- extract_one_exp_mi(survey_imp_male, setdiff(model3, "Sex"), "GIPSE_scaled")[, c("est", "CI", "pval", "paper_pval")]


table5_imp["female_model_2", c("index_eff", "index_95_CI", "index_pval", "index_paper_pval")] <- extract_one_exp_mi(survey_imp_female, setdiff(model2, "Sex"), "GISE_scaled")[, c("est", "CI", "pval", "paper_pval")]


table5_imp["female_model_3", c("index_eff", "index_95_CI", "index_pval", "index_paper_pval")] <- extract_one_exp_mi(survey_imp_female, setdiff(model3, "Sex"), "GIPSE_scaled")[, c("est", "CI", "pval", "paper_pval")]

table5_imp

write.csv(table5_imp, file = file.path(folder_path, "Results/like_supp_table1_whiirs.csv"))

```

```{r}
sessionInfo()
```